version: "2"

services:
  web:
    build:
      context: .
    ports:
      - "1230:1230"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
